export * from './panel-container-fake.component';
export * from './panel-fake.component';
export * from './panel-header-fake.component';
export * from './panel-body-fake.component';
export * from './panel-footer-fake.component';
export * from './panel-status-fake.service';
export * from './panel-fake.service';
export * from './panel-ref-fake.class';
export * from './panel-fake.module';
